baseURL = 'https://www.daedluz.com/'
languageCode = 'en-us'
title = 'Min Chun Chen'
theme = 'papermod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.assets]
  favicon = "assets/favicon.ico"

[params.homeInfoParams]
  Title = "Michael (Min Chen Chen)"
  Content = "Hello👋, welcome to my personal website! I am a computer science student interested in machine learning and data science research."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/daedluz"

[[params.socialIcons]]
  name = "email"
  url = "mailto:mchen12@umbc.edu"

[[params.socialIcons]]
  name = "linkedin" 
  url = "https://www.linkedin.com/in/michael-chen-8343981bb"

[[params.socialIcons]]
  name = "other"
  url = "https://sites.google.com/view/kekechen/researchtaic-lab"

